server:
  address: ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

logger:
  level: "all"
  stdout: true

database:
  logger:
    level: "all"
    stdout: true

  default:
    link: "mysql:root:winter+.0@tcp(127.0.0.1:3306)/gfdemo"
    debug: true
