# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  gen:
    dao:
      link: "mysql:root:winter+.0@tcp(127.0.0.1:3306)/gfdemo"
      removePrefix: "gf_"
      descriptionTag: true
      noModelComment: true
